apply plugin: 'java'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
}

dependencies {
    implementation (
        'com.amazonaws:aws-lambda-java-core:1.2.0',
        'com.amazonaws:aws-lambda-java-events:2.2.7',
        'com.amazonaws:aws-java-sdk-dynamodb:1.12.423',
        'org.slf4j:slf4j-api:1.8.0-beta2',
        'io.github.boostchicken:spring-data-dynamodb:5.2.5',
        'com.jayway.jsonpath:json-path:2.9.0'
    )
    runtimeOnly 'org.jlib:jlib-awslambda-logback:1.0.0'
}


task buildZip(type: Zip) {
    from compileJava
    from processResources
    into('lib') {
        from configurations.runtimeClasspath
    }
    archiveFileName = 'latest_build.zip'
}

build.dependsOn buildZip
