

package main.java.example
;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "OfficeEntry-f2sgeizrpjb7tmxb5pd7xnbcu4-staging")
public class OfficeEntry {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute(attributeName = "rotation")
    private int rotation;
    @DynamoDBAttribute(attributeName = "directEntrance")
    private boolean directEntrance;
    @DynamoDBAttribute(attributeName = "staircase")
    private boolean staircase;
    @DynamoDBAttribute(attributeName = "elevator")
    private boolean elevator;

    @DynamoDBAttribute(attributeName = "x")
    private int x;

    @DynamoDBAttribute(attributeName = "y")
    private int y;

    @DynamoDBAttribute(attributeName = "w")
    private int width;

    @DynamoDBAttribute(attributeName = "h")
    private int height;

    @DynamoDBAttribute(attributeName = "maxW")
    private int maxW;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    public OfficeEntry() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public int getRotation() {
        return rotation;
    }

    public void setRotation(int rotation) {
        this.rotation = rotation;
    }

    public boolean isDirectEntrance() {
        return directEntrance;
    }

    public void setDirectEntrance(boolean directEntrance) {
        this.directEntrance = directEntrance;
    }

    public boolean isStaircase() {
        return staircase;
    }

    public void setStaircase(boolean staircase) {
        this.staircase = staircase;
    }

    public boolean isElevator() {
        return elevator;
    }

    public void setElevator(boolean elevator) {
        this.elevator = elevator;
    }

    public int getX() {
        return x;
    }

    public void setX(int x) {
        this.x = x;
    }

    public int getY() {
        return y;
    }

    public void setY(int y) {
        this.y = y;
    }

    public int getWidth() {
        return width;
    }

    public void setWidth(int width) {
        this.width = width;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public int getMaxW() {
        return maxW;
    }

    public void setMaxW(int maxW) {
        this.maxW = maxW;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}