package main.java.example;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;



@DynamoDBTable(tableName = "Reservations-f2sgeizrpjb7tmxb5pd7xnbcu4-staging")
public class Reservations {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "userID")
    private String userId;

    @DynamoDBAttribute(attributeName = "spotID")
    private String spotId;

    @DynamoDBAttribute(attributeName = "date")
    private String date;


    public Reservations() {

    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getuId() {
        return userId;
    }

    public void setuId(String userId) {
        this.userId = userId;
    }

    public String getsId() {
        return spotId;
    }

    public void setsId(String spotId) {
        this.spotId = spotId;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

}
