package main.java.example;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "ParkingSpot-f2sgeizrpjb7tmxb5pd7xnbcu4-staging")
public class ParkingSpot {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "number")
    private int number;

    @DynamoDBAttribute(attributeName = "rotation")
    private int rotation;

    @DynamoDBAttribute(attributeName = "variant")
    private String variant;

    @DynamoDBAttribute(attributeName = "reversed")
    private boolean reversed;

    @DynamoDBAttribute(attributeName = "w")
    private int width;

    @DynamoDBAttribute(attributeName = "h")
    private int height;

    @DynamoDBAttribute(attributeName = "x")
    private int x;

    @DynamoDBAttribute(attributeName = "y")
    private int y;

    @DynamoDBAttribute(attributeName = "maxW")
    private int maxW;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    public ParkingSpot() {
    }


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public int getNumber() {
        return number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    public int getRotation() {
        return rotation;
    }

    public void setRotation(int rotation) {
        this.rotation = rotation;
    }

    public String getVariant() {
        return variant;
    }

    public void setVariant(String variant) {
        this.variant = variant;
    }

    public boolean isReversed() {
        return reversed;
    }

    public void setReversed(boolean reversed) {
        this.reversed = reversed;
    }

    public int getX() {
        return x;
    }

    public void setX(int x) {
        this.x = x;
    }

    public int getY() {
        return y;
    }

    public void setY(int y) {
        this.y = y;
    }

    public int getMaxW() {
        return maxW;
    }

    public void setMaxW(int maxW) {
        this.maxW = maxW;
    }

    public int getWidth() {
        return width;
    }

    public void setWidth(int width) {
        this.width = width;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


}

